name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GREETING: ${{ vars.GREETING }}
      NAME: ${{ vars.NAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run application
      run: node app.js
      env:
        GREETING: ${{ secrets.GREETING }}
        NAME: ${{ secrets.NAME }}
