name: Simple NodeJs
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    runs:
    using: 'node20'
    main: 'main.js'
    steps:
      - run: node --version
      - run: npm -version
      - uses: actions/checkout@v3
      - run: npm install
      - run: node app.js
