name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 20]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    #- name: Install dependencies
    - run: npm install express
    - run: npm install jest supertest --save-dev
    - run: npm install moment --save

    - name: Run tests
      run: npm test
      env:
        NODE_ENV: development
