---
  name: Hellow world using Node Js1
  on: push
  env:
    cloud: ${{ vars.PROJECT_ID }}
  jobs:
    first-job:
      runs-on: ubuntu-latest
      name: node:20
      steps:
        - run: node --version
        - run: npm -version
        - uses: actions/checkout@v3
        - run: npm install express
        - run: npm install jest supertest --save-dev
        - run: npm install moment --save
        - run: node app.js
        - run: echo "$cloud with project !"
  