name: Simple NodeJs
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    name:  node:16
    steps:
      - run: node --version
      - run: npm -version
      - uses: actions/checkout@v3
      - run: npm ci
      - run: node app.js
