name: Hellow world using Node Js
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    name:  node:16
    steps:
      - run: node --version
      - run: npm -version
      - uses: actions/checkout@v3
      - run: npm install express
      - run: npm install jest supertest --save-dev
      - run: npm install moment --save
      - run: node app.js
